language: c

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    packages:
      - libsnmp-dev
      - libwrap0-dev
      - libcurl4-gnutls-dev
      - libgenders0-dev

script:
 - ./autogen.sh
 - ./configure --with-genders --with-httppower --with-snmppower --with-tcp-wrappers
 - make distcheck
